FORMAT: 1A

# fonzie: an Open edX API

# Group Status

API status checking.

## Version [/status/version]

### Check API version [GET]

+ Request
    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "version": "0.1.0"
        }
